services:
  postgres:
    image: postgres:16
    container_name: hr_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
      POSTGRES_DB: hr_platform
    ports:  
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: