"""add cv_parsed_data to candidates

Revision ID: cceb47e2ceb3
Revises: e5ed49e4dd5b
Create Date: 2026-08-07 14:42:07.198321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cceb47e2ceb3'
down_revision: Union[str, Sequence[str], None] = 'e5ed49e4dd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('cv_parsed_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'cv_parsed_data')
    # ### end Alembic commands ###
