"""add processing status to candidates

Revision ID: d1ea096507cb
Revises: f47d1d60c890
Create Date: 2026-08-15 19:11:04.098696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ea096507cb'
down_revision: Union[str, Sequence[str], None] = 'f47d1d60c890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('processing_status', sa.String(), nullable=False , server_default='pending'))
    op.add_column('candidates', sa.Column('processing_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'processing_error')
    op.drop_column('candidates', 'processing_status')
    # ### end Alembic commands ###
