"""add cv_file_path and cv_raw_text to candidates

Revision ID: e5ed49e4dd5b
Revises: e7f5d87a99bb
Create Date: 2026-08-07 12:42:50.604005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ed49e4dd5b'
down_revision: Union[str, Sequence[str], None] = 'e7f5d87a99bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('cv_file_path', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('cv_raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'cv_raw_text')
    op.drop_column('candidates', 'cv_file_path')
    # ### end Alembic commands ###
