"""add embedding vector columns to jobs and candidates

Revision ID: f47d1d60c890
Revises: cceb47e2ceb3
Create Date: 2026-08-08 15:58:54.551395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy




# revision identifiers, used by Alembic.
revision: str = 'f47d1d60c890'
down_revision: Union[str, Sequence[str], None] = 'cceb47e2ceb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.add_column('candidates', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('jobs', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding')
    op.drop_column('candidates', 'embedding')
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
